### ISSUE TITLE
请问这个可以用来做网络的极限测试吗

### ISSUE THREAD

**Issue by larsonzhong** [guonaihong/gurl#1]
我想测试一下我连接的基站的最大承压带宽是多少，可以用gurl来测试吗

**Comment by guonaihong** [comment]
对于基站只是听过，没接触过，只是按压测服务的套路给些建议。

如果要压流量的话，在压测的另一端准备一个http服务端，可以用
`gurl -l :port &>/dev/null`
客户端
`gurl -bench -ac 25 -duration 1m -d @file -url http://xxx.xxx.xxx.xxx:port`
表示，每个线程(其实是协程很轻量) 打开一个file 文件，一共25线程发送，发完就继续发，等到1分钟结束就不发。其中的file文件可以用dd文件生成一个。
